healthcare_project:
  outputs:
    dev:
      type: duckdb
      path: 'database.duckdb'  # Local file
      extensions:
        - httpfs
        - iceberg
      settings:
        s3_endpoint: 'minio:9000'
        s3_access_key_id: 'admin'
        s3_secret_access_key: 'password123'
        s3_use_ssl: false
  target: dev