connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://nessie:19101/api/v1
iceberg.nessie-catalog.default-warehouse-dir=s3://healthcare/iceberg
fs.native-s3.enabled=true
s3.endpoint=${ENV:AWS_ENDPOINT_URL}
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
iceberg.register-table-procedure.enabled=true
